# Generated by Django 4.0.1 on 2022-02-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerHBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
    ]
